Add tests
kernc/mdx_unimoji pull request #2
Opened 2016-09-17 10:44 UTC by blag

I think there's a race condition in here somewhere, but the tests do pass for the majority of Python versions.

2016-09-17 20:12 UTC, kernc commented
Thanks. What race condition?

2016-09-17 20:13 UTC, kernc commented on .travis.yml
> +  # - PYTHONPATH=. python tests.py
Can we get rid of these commented lines?

2016-09-17 20:13 UTC, kernc commented on tests/with_both_options.py
> +        # self.assertEqual(should_be, result)
And here.

2016-09-17 20:17 UTC, kernc commented on tests/without_mdx_unimoji_extension.py
> +    def test_markdown_without_emoji_extension(self):
Could short tests like these be merged into a single file? It seems somewhat redundant to have them in separate files when the method name itself seems to convey action sufficiently.

2016-09-17 20:18 UTC, kernc commented on tests/with_span_class_option_none.py
> +        from mdx_unimoji import UnimojiExtension
Why wouldn't the imports be global at the top of the file?

2016-09-17 20:19 UTC, kernc commented on tests/with_span_class_option.py
> +        text = 'I <3 you! Just kidding. :P'
You are invited to think up a more _optimistic_ test string. I insist.

2016-09-17 20:19 UTC, kernc requested changes

2016-09-17 20:32 UTC, blag commented on tests/without_mdx_unimoji_extension.py
> +    def test_markdown_without_emoji_extension(self):
Nope. I tried that, but then I started to get errors like this:

```python
ERROR: test_mdx_span_class_option (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 55, in test_mdx_span_class_option
    result = markdown(text, extensions=[UnimojiExtension(span_class='other')])
  File ".../mdx_unimoji.py", line 117, in __init__
    super(UnimojiExtension, self).__init__(*args, **kwargs)
  File ".../lib/python3.5/site-packages/markdown/extensions/__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
  File ".../lib/python3.5/site-packages/markdown/extensions/__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
  File ".../lib/python3.5/site-packages/markdown/extensions/__init__.py", line 73, in setConfig
    value = parseBoolValue(value, preserve_none=True)
  File ".../lib/python3.5/site-packages/markdown/util.py", line 111, in parseBoolValue
    raise ValueError('Cannot parse bool value: %r' % value)
ValueError: Cannot parse bool value: 'other'
```

When I keep the tests in different files and run them separately they pass.

2016-09-17 20:33 UTC, blag commented on .travis.yml
> +  # - PYTHONPATH=. python tests.py
Sure.

2016-09-17 20:34 UTC, blag commented on tests/with_both_options.py
> +        # self.assertEqual(should_be, result)
This test never passes, but I included it commented out so others might be able to get it to pass. I'll remove it.

2016-09-17 20:37 UTC, blag commented on tests/with_span_class_option_none.py
> +        from mdx_unimoji import UnimojiExtension
When debugging I suspected `markdown` was doing something janky and trying to cache extensions or something. I'll move them.

2016-09-17 20:39 UTC, kernc commented on tests/with_both_options.py
> +        # self.assertEqual(should_be, result)
You could use `unittest.skip()`.

2016-09-17 20:39 UTC, blag commented on tests/with_span_class_option.py
> +        text = 'I <3 you! Just kidding. :P'
Um, okay. That test string is perfect because it checks the red style on the heart and the smiley faces, but sure.

2016-09-17 20:56 UTC, blag commented
Here's my evidence of a race condition. These are the results when `should_be` is

    <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>

```
======================================================================
FAIL: test_mdx_overrides_emoji_option (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/with_emoji_overrides_option.py", line 25, in test_mdx_overrides_emoji_option
    self.assertEqual(should_be, result)
AssertionError: '<p>I[58 chars]t kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>' != '<p>I[58 chars]t kidding. <span class="emoji">😛</span></p>'
- <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>
?                                                                           ^^^^ ^^^^^^^              ^ ^^^^^^ ----------
+ <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <span class="emoji">😛</span></p>
?                                                                           ^^ ^              ^^^^ ^^
```

so then I changed `should_be` to

    <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <span class="emoji">😛</span></p>

and it passed:

```
----------------------------------------------------------------------
Ran 1 test in 0.021s

OK
```

and I ran it again without changing *anything* and it failed:

```
======================================================================
FAIL: test_mdx_overrides_emoji_option (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/with_emoji_overrides_option.py", line 25, in test_mdx_overrides_emoji_option
    self.assertEqual(should_be, result)
AssertionError: '<p>I[58 chars]t kidding. <span class="emoji">😛</span></p>' != '<p>I[58 chars]t kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>'
- <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <span class="emoji">😛</span></p>
?                                                                           ^^ ^              ^^^ ----
+ <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>
?
```

and I ran it again and it failed with a different error:

```
======================================================================
FAIL: test_mdx_overrides_emoji_option (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/with_emoji_overrides_option.py", line 25, in test_mdx_overrides_emoji_option
    self.assertEqual(should_be, result)
AssertionError: '<p>I <img alt="love" class="emoji" src="heart.p[54 chars]</p>' != '<p>I <span class="emoji" style="color:red">❤</s[52 chars]</p>'
- <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <span class="emoji">😛</span></p>
?       ^^^^ ^^^^^^^^^                ^^  ^  ---- ----
+ <p>I <span class="emoji" style="color:red">❤</span> you! Just kidding. <span class="emoji">😛</span></p>
?       ^^ ^                ^^^^  ^^^^^^^ ++++++++
```

and I ran it one more time and got a different error:

```
======================================================================
FAIL: test_mdx_overrides_emoji_option (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/with_emoji_overrides_option.py", line 25, in test_mdx_overrides_emoji_option
    self.assertEqual(should_be, result)
AssertionError: '<p>I <img alt="love" class="emoji" src="heart.p[54 chars]</p>' != '<p>I <span class="emoji" style="color:red">❤</s[71 chars]</p>'
- <p>I <img alt="love" class="emoji" src="heart.png" /> you! Just kidding. <span class="emoji">😛</span></p>
+ <p>I <span class="emoji" style="color:red">❤</span> you! Just kidding. <img alt=":P" class="emoji" src="tongue.png" /></p>
```

So unless `mdx_unimoji` explicitly relies on random functionality, this just screams "race condition!" at me. I don't have enough free time to debug this though.

2016-09-17 23:59 UTC, blag commented
Yeah, there's something going on that looks like a race condition. The test results for [this PR](https://travis-ci.org/kernc/mdx_unimoji) and [my repo](https://travis-ci.org/blag/mdx_unimoji) yield different results with the exact same code.

Changing an unrelated file and rerunning the tests yields differing results.

At this point I've taken care of the issues you've noted, and the scope of this PR (adding tests) is complete. Please merge unless you have any more suggestions.

2016-09-18 05:09 UTC, blag commented on tests/with_both_options.py
> +        # self.assertEqual(should_be, result)
I got it to work instead of skipping it. 👍

2019-01-12 10:17 UTC, closed without merging

2019-01-12 10:44 UTC, kernc commented
Since this extension (had) extended Markdown in an officially-recommended manner and since it primarily consists of a [simple, linear, single-threaded routine](https://github.com/kernc/mdx_unimoji/blob/5225b1d31485fe58a7156578736b747d9fa278d2/mdx_unimoji.py#L138-L159), any misbehavior (race conditions) should be attributed to [Markdown](https://github.com/Python-Markdown/markdown) itself.